### ISSUE TITLE
Panic in `repeatString` when repeating an empty string more than `9223372036854775807 - 512` times

### ISSUE THREAD

**Issue by cwwarren** [itchyny/gojq#209]
There is an overflow causing a panic present when an empty string is repeated more than `9223372036854775807 - 512` times.

The overflow leading to a negative count happens when the `float64` is cast to `int` ([Go Playground Example](https://go.dev/play/p/A8ScyRvpZ5z)).

Reproduction:

```
% echo '{}' | gojq '"" * (9223372036854775807 - 512)'
""
% echo '{}' | gojq '"" * (9223372036854775807 - 511)'
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat({0x0?, 0x100a285?}, 0x8?)
	strings/strings.go:538 +0x4d8
github.com/itchyny/gojq.repeatString({0x0?, 0xc00001ea10?}, 0x7fffffff0000f8c0?)
	github.com/itchyny/gojq/operator.go:442 +0x9b
github.com/itchyny/gojq.funcOpMul.func6({0x11d27a0?, 0x138d5a0?}, {0x11d2020?, 0xc00001ea10?})
	github.com/itchyny/gojq/operator.go:404 +0x18c
github.com/itchyny/gojq.binopTypeSwitch({0x11d27a0?, 0x138d5a0?}, {0x11d2020?, 0xc00001ea10?}, 0x17c8938?, 0x120c8e0?, 0x120c8e8?, 0x11e4900?, 0x1?, 0x120c5a8, ...)
	github.com/itchyny/gojq/operator.go:258 +0xee
github.com/itchyny/gojq.funcOpMul({0x1012d05?, 0x100a634?}, {0x11d27a0?, 0x138d5a0?}, {0x11d2020?, 0xc00001ea10?})
	github.com/itchyny/gojq/operator.go:388 +0x85
github.com/itchyny/gojq.argFunc2.func1({0x11dafa0?, 0xc00013de60?}, {0xc00016c8e0?, 0x2?, 0x6c0?})
	github.com/itchyny/gojq/func.go:220 +0x4d
github.com/itchyny/gojq.(*env).Next(0xc00016c840)
	github.com/itchyny/gojq/execute.go:192 +0x3e5d
github.com/itchyny/gojq/cli.(*cli).printValues(0xc000172000, {0x1248108, 0xc00016c840})
	github.com/itchyny/gojq/cli/cli.go:359 +0x46
github.com/itchyny/gojq/cli.(*cli).process(0xc000172000, {0x1248a58, 0xc00010a780}, 0x0?)
	github.com/itchyny/gojq/cli/cli.go:349 +0x149
github.com/itchyny/gojq/cli.(*cli).runInternal(0xc000172000, {0xc000014050, 0x1, 0x1})
	github.com/itchyny/gojq/cli/cli.go:274 +0x1cd6
github.com/itchyny/gojq/cli.(*cli).run(0x1005b39?, {0xc000014050?, 0x0?, 0x0?})
	github.com/itchyny/gojq/cli/cli.go:88 +0x27
github.com/itchyny/gojq/cli.Run(...)
	github.com/itchyny/gojq/cli/run.go:11
main.main()
	github.com/itchyny/gojq/cmd/gojq/main.go:11 +0xf8
```

**Comment by itchyny** [comment]
Now fixed the issue, thanks for reporting.
